daksha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('rank.urls', 'rank'), namespace='rank')),
]

rank/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
	#path('register/', views.reg_closed, name='register_page'),
	#path('events/',views.event, name='event'),
	#path('',views.index, name='index'),
	#path('export/csv/', views.export_users_csv, name='export_users_csv'),
	#path('team/',views.team, name='team'),
	path('',views.result_view,name='result'),
	path('export/csv/', views.export_result_csv, name='export_result_csv'),
]

rank/models.py
from django.db import models
from multiselectfield import MultiSelectField
# Create your models here.


'''class Registration(models.Model):

	EVENTS_CHOICES = (
	('kadaprasangham', 'KADHAPRASANGAM'),
	('monoact', 'MONOACT'),
	('western_solo', 'WESTERN SOLO'),
	('mappila', 'MAPPILAPATTU'),
	('mimicry', 'MIMICRY'),
	('naadoodinritham', 'NAADODINIRTHAM'),
	('ottamthulla', 'OTTANTHULLAL'),
	('bharathanatyam', 'BHARATHANATYAM'),
	('mohiniyattam', 'MOHINIYATTAM'),
	('speech_eng', 'SPEECH ENGLISH'),
	('speech_mal', 'SPEECH MALAYALAM'),
	('speech_hin', 'SPEECH HINDI'),
	('violin', 'VIOLIN'),
	('veena', 'VEENA'),
	('organ', 'ORGAN'),
	('thabala', 'THABALA'),
	('guitar', 'GUITAR'),
	('mrithangam', 'MRITHANGAM'),
	('kavitha_mal', 'KAVITHA MALAYALAM'),
	('poem_eng', 'POEM ENGLISH'),
	('poem_hin', 'POEM HINDI'),
	('poem_arab', 'POEM ARABIC'),
	('poem_sanskrit', 'POEM SANSKRIT'),
	('lightmusic','LIGHT MUSIC'),
	('classic_music','CLASSICAL MUSIC'),
	('kuchipudi', 'KUCHIPUDI'))

	YEAR_CHOICES = (
		('1', '1'),
		('2', '2'),
		('3', '3'),
		('4', '4'),
		('Mtech', 'M.Tech'),)

	DEPARTMENT_CHOICES = (
		('CSE', 'Computer Science'),
		('IT', 'Information Technology'),
		('ECE', 'Electronics and Communication'),
		('EEE', 'Electrical and Electronics'),
		('ME', 'Mechanical Engineering'))


	#Registation Table
	full_name = models.CharField(max_length=50)
	year = models.CharField(default ='2',max_length=10, choices=YEAR_CHOICES)
	department = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES, default='Computer Science')
	phone = models.CharField(max_length=12, null=True)
	events = MultiSelectField(choices=EVENTS_CHOICES, max_choices=4, default='KADHAPRASANGAM')

	def __str__(self):
		return self.full_name

	def __unicode__(self):
		return self.full_name'''

class OnstageResult(models.Model):

	#Result Table
	event_name = models.CharField(max_length=50,default=None)
	first_prize = models.TextField(default=None)
	second_prize = models.TextField(default=None)
	third_prize = models.TextField(default=None)

	def __str__(self):
		return self.event_name

	def __unicode__(self):
		return self.event_name

class OffstageResult(models.Model):

	#Result Table
	event_name = models.CharField(max_length=50,default=None)
	first_prize = models.TextField(default=None)
	second_prize = models.TextField(default=None)
	third_prize = models.TextField(default=None)

	def __str__(self):
		return self.event_name

	def __unicode__(self):
		return self.event_name


class Point(models.Model):

	#Points Table:
	year = models.CharField(max_length=50,default=None)
	points =  models.DecimalField(default =0,max_digits=3,decimal_places=0)

	def __str__(self):
		return self.points

	def __str__(self):
		return self.year

rank/forms.py
from django.forms import ModelForm

'''from . models import Registration
class RegistrationForm(ModelForm):
	class Meta:
		model = Registration
		fields = ['full_name','year','department','phone','events']
		'''

daksha/views.py
from django.shortcuts import render,redirect



rank/views.py
from django.shortcuts import render
from . models import Point, OnstageResult, OffstageResult
import csv
from django.http import HttpResponse

# Create your views here

'''def index(request):
	return render(request, 'index.html')

def event(request):
		return render(request, 'events.html')

def team(request):
		return render(request, 'team.html')

def register_page(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			new_data = form.save()
			return render(request, 'rank/register_success.html')
	else:
		form = RegistrationForm()
	return render(request, 'rank/register.html', {'form':form})


def score_view(request):

	queryset = Point.objects.all()
	context = {"score" : queryset }

	return render(request,"score.html",context)'''


# new
def result_view(request):
    queryset3 = OffstageResult.objects.all()
    queryset2 = Point.objects.all()
    queryset = OnstageResult.objects.all()
    dict = {"onresult": queryset, "offresult": queryset3, "point": queryset2}
    # print(type(dict['result'].event_name))
    return render(request, "results.html", dict)


'''def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'

    writer = csv.writer(response)
    writer.writerow(['full_name', 'year', 'department', 'phone', 'events'])

    lists = Registration.objects.all().values_list('full_name', 'year', 'department', 'phone', 'events')
    for entry in lists:
        writer.writerow(entry)

    return response
def reg_closed(request):
	return render(request, 'rank/register_success.html')'''


def export_result_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="DakshaSiteResults.csv"'

    writer = csv.writer(response)
    writer.writerow(['Onstage Event', 'First', 'Second', 'Third'])

    lists = OnstageResult.objects.all().values_list(
        'event_name', 'first_prize', 'second_prize', 'third_prize')
    for entry in lists:
        writer.writerow(entry)

    writer.writerow([''])
    writer.writerow(['Offstage Event', 'First', 'Second', 'Third'])
    lists = OffstageResult.objects.all().values_list(
        'event_name', 'first_prize', 'second_prize', 'third_prize')
    for entry in lists:
        writer.writerow(entry)

    return response

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>About Us</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Alumni Portal</title>
	<link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129276229-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-129276229-1');
	</script>

</head>
<body>
	<header>
								<nav class="navbar navbar-expand-md navbar navbar-dark bg-dark navbar sticky-top">
								<div class="container-fluid">
							<span class="navbar-brand mb-0 h1" id="heading">RESOLUTE COLLEGE UNION</span>
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse" id="navbarResponsive">

							<ul class="navbar-nav ml-auto">
									<li class="nav-item active">
							<!--  <a class="nav-link" href="#">Results</a>
								</li>-->
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:index" %}">Home</a>
							</li>
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:team" %}">Team</a>
								</li>
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:event" %}">Event Lists</a>
								</li>
								<!-- <li class="nav-item">
	                <a class="nav-link" href="{% url "rank:result" %}">Results</a>
	              </li> -->

						</ul>
								</div>
							</div>
						</nav>
						</header>

<!-- meet the team -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Meet The Team</h1>
			<hr>
		</div>
	</div>
</div>
<!-- frontend -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h3>Front-End</h3>
		</div>
	</div>
</div>
<br>
<!-- flipcards -->
<div class="container-fluid padding">
	<div class="row padding">
		<div class="col-md-4">
			<div class="res">
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img/vishnu.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Vishnu</h1>
      <p class="lead">Information & Technology</p>
      <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
</div>
<br>
<div class="col-md-4">
	<div class="res">
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img/aravind.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Aravind</h1>
       <p class="lead">Electronics & Communication</p>
      <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
</div>
<br>
<div class="col-md-4">
	<div class="res">
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img/Abi.jpg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Abhijith A</h1>
      <p class="lead">Electronics & Communication</p>
      <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
<!-- backend -->
<br>
<br>
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h3>Back-End</h3>
		</div>
	</div>
</div>
<br>
<!-- flip cards -->

<div class="container-fluid padding">
	<div class="row padding">

		<div class="col-lg-6">
			<div class="left">
			<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img/rejul.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Rejul</h1>
      <p class="lead">Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
</div>


		<div class="col-lg-6">
			<div class="right">
		<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="img/Ajay.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Ajay Dev</h1>
      <p class="lead">Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
	</div>
</div>
</div>
<br>
<br>

<footer>
    <div class="footer-bottom text-center">
      Made With <img src="{% static "./img/purple-heart_1f49c.png"%}" style="height:25px;width:25px"> at GEC Palakkad <br> ./tech_team
    </div>
  </footer>





<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleeapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/flipclock.css'%}">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="{% static 'js/flipclock.js'%}"></script>
  <script src="{% static 'js/jquery.countdown.js'%}"></script>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'>
  <title> DAKSHA'18 |YAGA OF ART </title>
  <link rel = "icon" type = "image/jpg" href = "/bg2.jpg">
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129276229-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-129276229-1');
</script>

</head>

<body>

  <!-- Showcase & Nav -->
  <header>
                <nav class="navbar navbar-expand-md navbar navbar-dark bg-dark navbar sticky-top">
                <div class="container-fluid">
              <span class="navbar-brand mb-0 h1" id="heading">RESOLUTE COLLEGE UNION</span>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">

              <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
              <!--  <a class="nav-link" href="#">Results</a>
                </li>-->
                <li class="nav-item">
                <a class="nav-link" href="{% url "rank:team" %}">Team</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url "rank:event" %}">Event Lists</a>
                </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url "rank:result" %}">Results</a>
              </li> 
            </ul>
                </div>
              </div>
            </nav>
            </header>

 <div id="showcase">

    <div class="section-main container">
      <h1>DAKSHA 2K18</h1>
      <h2>21,22 NOV</h2>
      <br><br><br>
   <a href="{% url "rank:result" %}"><button type="button" class="btn btn-outline-light btn-lg">View Results</button></a>
     </div>
    </div>


  <section id="music" class="section">
    <div class="container">
      <!--<h2 class="section-head">
       The Yaga Of Art Starts In
      </h2>-->
      <div class="count_container"> <div class="clock" style="margin:2em;"></div></div>
      <div class="counter"></div><img src={%static './img/line.png'%}>

    </div>
  </section>

  <!--<div class="container-fluid padding">
	<div class="row text-center padding">
		<div class="col-12">
			<h2>Connect</h2>
		</div>
		<div class="col-12 social padding">
		<a href="https://www.facebook.com/lifeatgec"><i class="fab fa-facebook"></i></a>
			<a href="https://www.instagram.com/lifeatgec/"><i class="fab fa-instagram"></i></a>
		</div>
	</div>
</div> -->



  <!-- Footer -->
  <footer>
    <div class="footer-bottom text-center">
      Made With <img src="{% static "./img/purple-heart_1f49c.png"%}" style="height:25px;width:25px"> at GEC Palakkad <br> ./tech_team
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script type="text/javascript">

		$(document).ready(function() {
			var clock;
      var now=new Date().getTime();
      //var n=now.getTime();
      var event=new Date(2018,10,21).getTime();
     // var e=e.getTime();
      var a=event-now;

			clock = $('.clock').FlipClock({
		        clockFace: 'DailyCounter',
		        autoStart: false,
		        callbacks: {
		        	stop: function() {
		        		$('.message').html('The clock has stopped!')
		        	}
		        }
		    });

		    clock.setTime(a/1000);
		    clock.setCountdown(true);
        clock.start();

        $('.counter').countdown('2018/11/21', function(event) {
        $(this).html(event.strftime('%w weeks %d days %H:%M:%S'));

    });
  });
	</script>
</body>

</html>

templates/team.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>About Us</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Alumni Portal</title>
	<link href="https://fonts.googleapis.com/css?family=Rajdhani" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'about/css/style.css' %}">


	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129276229-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());
	  gtag('config', 'UA-129276229-1');
	</script>
</head>
<body>
	<header>
								<nav class="navbar navbar-expand-md navbar navbar-dark bg-dark navbar sticky-top">
								<div class="container-fluid">
							<span class="navbar-brand mb-0 h1" id="heading">RESOLUTE COLLEGE UNION</span>
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse" id="navbarResponsive">

							<ul class="navbar-nav ml-auto">
									<li class="nav-item active">
							<!--  <a class="nav-link" href="#">Results</a>
								</li>-->
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:index" %}">Home</a>
							</li>
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:team" %}">Team</a>
								</li>
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:event" %}">Event Lists</a>
								</li>
								<li class="nav-item">
								<a class="nav-link" href="{% url "rank:result" %}">Results</a>
							</li> 
						</ul>
								</div>
							</div>
						</nav>
						</header>

<!-- meet the team -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Meet The ./tech_team</h1>
			<hr>
		</div>
	</div>
</div>
<!-- frontend -->

<br>

<!-- flipcards -->
<div class="container-fluid padding">
	<div class="row padding">
				<div class="info_c">
					<div class="img_u"><img class="img-circle" src="{% static 'about/img/vishnu.jpeg' %}" alt="Avatar" ></div>
					<div class="info">
						<h1>VISHNU</h1>
					       <p class="lead">S5 Information Technology</p>
					      <p class="lead">Govt. Engineering college</p>
					      <p class="lead">Sreekrishnapuram</p>
								<p class="lead">Front-End Developer</p>
					</div>

				</div>


<br>
<div class="info_c">
	<div class="img_u" ><img class="img-circle" src="{% static 'about/img/aravind.jpeg' %}" alt="Avatar" ></div>
					<div class="info" >
						<h1>Aravind</h1>
       <p class="lead">S5 Electronics & Communication</p>
      <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
<p class="lead">Front-End Developer</p>
		</div>


				</div>


<br>
<div class="info_c">
	<div class="img_u"><img class="img-circle" src="{% static 'about/img/Abi.jpg' %}" alt="Avatar" ></div>
					<div class="info">
						<h1>Abhijith A</h1>
      <p class="lead">S5 Electronics & Communication</p>
      <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
			<p class="lead">Front-End Developer</p>
					</div>

				</div>



<br>
<div class="info_c">
	<div class="img_u"><img class="img-circle" src="{% static 'about/img/margs.jpg' %}" alt="Avatar" ></div>
					<div class="info">
						<h1>Varsha Margrette</h1>
			<p class="lead">S7 Information Technology</p>
				<p class="lead">Govt. Engineering college</p>
			<p class="lead">Sreekrishnapuram</p>
			<p class="lead">Back-End Developer</p>
					</div>

				</div>


<br>
<div class="info_c">
	<div class="img_u"><img class="img-circle" src="{% static 'about/img/rejul.jpeg' %}" alt="Avatar" ></div>
					<div class="info">
						<h1>Rejul S</h1>
      <p class="lead">S5 Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
		<p class="lead">Back-End Developer</p></div>

				</div>


<br>
<div class="info_c">
	<div class="img_u"><img class="img-circle" src="{% static 'about/img/Ajay.jpeg' %}" alt="Avatar" ></div>
					<div class="info">
						<h1>Ajay Dev</h1>
      <p class="lead">S5 Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
			<p class="lead">Back-End Developer</p>
					</div>

				</div>


<br>


</div>
</div>
<!-- backend -->

<!-- flip cards -->

<!-- <div class="container-fluid padding">
	<div class="row padding">
		<div class="col-lg-6">
			<div class="left">
			<div class="flip-card">
	<div class="flip-card-inner">
		<div class="flip-card-front">
			<img src="about/img/margs.jpeg" alt="Avatar" style="width:300px;height:300px;">
		</div>
		<div class="flip-card-back">
			<h1>Varsha Margrette</h1>
			<p class="lead">S7 Information Technology</p>
				<p class="lead">Govt. Engineering college</p>
			<p class="lead">Sreekrishnapuram</p>
		</div>
	</div>
	</div>
	</div>
	</div>
		<div class="col-lg-6">
			<div class="res">
			<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="about/img/rejul.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Rejul S</h1>
      <p class="lead">S5 Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div></div>
		<div class="col-lg-6">
			<div class="right">
		<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="about/img/Ajay.jpeg" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <h1>Ajay Dev</h1>
      <p class="lead">S5 Computer Science & Engineering</p>
        <p class="lead">Govt. Engineering college</p>
      <p class="lead">Sreekrishnapuram</p>
    </div>
  </div>
</div>
</div>
	</div>
</div>
</div> -->
<br>
<br>

<footer>
    <div class="footer-bottom text-center">
      Made With <img src="{% static './img/purple-heart_1f49c.png' %}" style="height:25px;width:25px"> at GEC Palakkad <br> ./tech_team
    </div>
  </footer>





<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleeapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

</body>
</html>